#!/usr/bin/python

# <input video> <output.webm>

# missing a mode for /my/pic/moviecam/ari-garage.avi, maybe others

import sys, subprocess, os
inPath, outPath = sys.argv[1:]

if inPath.endswith(".mp4"):
    # pre phone cam
    ARGS="-threads 16  -keyint_min 0 -r 30000/1001 -g 250 -skip_threshold 0 -qmin 1 -qmax 51".split() + [
        "-i", inPath,
        "-vcodec", "libvpx",
        "-b", "500000",
        "-s", "320x240"]
elif inPath.endswith((".AVI", ".avi")):
    # nikon digicam
    ARGS="-threads 16  -keyint_min 0 -r 30000/1001 -g 250 -skip_threshold 0 -qmin 1 -qmax 51".split() + [
        "-i", inPath,
        "-vcodec", "libvpx",
        "-b", "500000",
        "-ar", "44000", # per http://ffmpeg-users.933282.n4.nabble.com/ffmpeg-fails-to-create-webm-content-if-audio-bitrate-is-less-than-44K-td2303313.html
        "-s", "320x212"]
    
LOGBASE="/tmp/vid-%s" % os.getpid()

subprocess.check_call(['/usr/local/bin/ffmpeg', '-pass', '1', '-passlogfile', LOGBASE] + ARGS + ['-an', '-f', 'rawvideo', '-y', '/dev/null'])
subprocess.check_call(['/usr/local/bin/ffmpeg', '-pass', '2', '-passlogfile', LOGBASE] + ARGS + ['-acodec', 'libvorbis', '-y', outPath])
