#!/usr/bin/python

"""
calls photos.justCache on one image; meant for farm jobs
"""

import sys, photos
url = sys.argv[1]
sizes = map(int, sys.argv[2:])
try:
    photos.justCache(url, sizes)
except Exception:
    print >>sys.stderr, "argv: %r" % sys.argv
    raise
