#!/usr/bin/python
"""
read a tree of the filesystem and write rdf about the images we find

 uri a foaf:Image
 uri :inDirectory dir
 dir a :DiskDirectory
 dir :inDirectory dir
 uri :filename basename

"""
import sys, os, urllib
from rdflib.Graph import ConjunctiveGraph
from rdflib import Namespace, RDF, RDFS, URIRef, Literal

PHO = Namespace("http://photo.bigasterisk.com/0.1/")
SITE = Namespace("http://photo.bigasterisk.com/")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")

def uriOfFilename(rootUri, root, filename):
    prefix = root.rstrip('/')
    if not filename.startswith(prefix):
        raise ValueError("%s doesn't start with %s" % (filename, prefix))
    relFile = filename[len(prefix):]
    return URIRef(rootUri + urllib.quote(relFile))

def goodDirNames(names):
    ret = []
    for name in names:
        if not (name.startswith('.') or name.startswith('~')):
            ret.append(name)
    return ret

def filenameIsImage(filename):
    for ext in ['.jpg', '.gif']:
        if filename.lower().endswith(ext):
            return True
    return False

## def addDirStatements(graph, subdirAbs, rootUri, dirUri):
##     subdirUri = uriOfFilename(rootUri, root, subdirAbs)
##     graph.add((subdirUri, RDF.type, PHO['DiskDirectory']))
##     graph.add((subdirUri, PHO[        addDirStatements(graph, dirpath, rootUri, dirUri)        addDirStatementsaddDirStatements(graph, dirpath, rootUri, dirUri)'filename        addDirStatements(graph, dirpath, rootUri, dirUri)'], Literal(subdir)))
    
##     graph.add((dirUri, RDF.type, PHO['DiskDirectory']))
##     graph.add((dirUri, PHO['filename'],
##                Literal(os.path.basename(dirpath))))
##     graph.add((subdirUri, PHO['inDirectory'], dirUri))

def main(root, topDir='/my/pic'):
    root = os.path.abspath(root)
    assert root.startswith(topDir) or root == topDir

    graph = ConjunctiveGraph()
    
    rootUri = SITE[root[len(topDir) + len('/'):]]
    for dirpath, dirnames, filenames in os.walk(root, topdown=True):
        print >>sys.stderr, "visit", dirpath

        dirnames[:] = goodDirNames(dirnames)

        dirUri = uriOfFilename(rootUri, root, dirpath)
        graph.add((dirUri, RDF.type, PHO['DiskDirectory']))
        graph.add((dirUri, PHO['filename'], Literal(dirpath)))
        
        for subdir in dirnames:
            subdirAbs = os.path.abspath(os.path.join(dirpath, subdir))
            subdirUri = uriOfFilename(rootUri, root, subdirAbs)
            graph.add((dirUri, PHO['inDirectory'], subdirUri))

        for filename in filenames:
            if not filenameIsImage(filename):
                continue
            fileUri = uriOfFilename(rootUri, root,
                                    os.path.abspath(os.path.join(dirpath,
                                                                 filename)))
            graph.add((fileUri, RDF.type, FOAF['Image']))
            graph.add((fileUri, PHO['inDirectory'], dirUri))
            graph.add((fileUri, PHO['filename'], Literal(filename)))

    print >>sys.stderr, "done, writing %d triples" % len(graph)
    print graph.serialize(format='nt')

main(sys.argv[1])
